# status bar on top
set-option -g status-position top

# start window numbering at 1
set-option -g base-index 1

# start pane numbering at 1
set-option -g pane-base-index 1

# renumber windows after closing
set-option -g renumber-windows on

# enables mouse support inside tmux
set -g mouse on

# enables support for extended keyboard sequences
# set -g xterm-keys on

# tmux doesnt wait after Esc is pressed
set -s escape-time 0

# enables truecolor (24-bit color)
set -ga terminal-overrides ",*:Tc"

# Left: session name, dim
set -g status-left "#[fg=colour244,bg=#2e323c] #S "

# Right: pane title/path-like info, dim, no clock/date
set -g status-right '#[fg=colour244,bg=#2e323c]#{?window_bigger,[#{window_offset_x}#,#{window_offset_y}] ,}"#{=21:pane_title}" '

# Center window tabs
set -g status-justify centre

# Inactive tabs: dim grey, no special marker
set -g window-status-style "fg=colour244,bg=#2e323c"
set -g window-status-format " #I:#W "

# Active tab: tmux green, no *
# set -g window-status-current-style "fg=#6A9955,bg=#2e323c,bold"
set -g window-status-current-style "fg=#A6E22E,bg=#2e323c,bold"
set -g window-status-current-format " #I:#W "
set -g status-style "fg=colour135,bg=#2e323c"
