# status bar on top
set-option -g status-position top

# start window numbering at 1
set-option -g base-index 1

# start pane numbering at 1
set-option -g pane-base-index 1

# renumber windows after closing
set-option -g renumber-windows on

# enables mouse support inside tmux
set -g mouse on

# enables support for extended keyboard sequences
# set -g xterm-keys on

# tmux doesnt wait after Esc is pressed
set -s escape-time 0

# enables truecolor (24-bit color)
set -ga terminal-overrides ",*:Tc"
